name: build_windows Vistar

on:
  push:
    branches:
      - main

jobs:
  Call_Selenium_For_Registration:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pyinstaller
        # Add any other dependencies your script might have
    - name: install
      run: |
        pip install selenium

    - name: Build executable
      run: |
        pyinstaller --onefile gmail.py
        # Replace 'gmail.py' with the actual name of your Python script

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gmail
        path: ./dist/gmail.exe  # Adjust the path to store in the root directory
