name: Build Exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pyinstaller
        # Add any other dependencies your script might have

    - name: Build executable
      run: |
        pyinstaller --onefile gmail.py
        # Replace 'gmail.py' with the actual name of your Python script

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gmail
        path: dist/gmail.exe  # Replace 'your_script' with the name of the executable
